# Remaining compound profiles (data only) consumed by build_compounds.py::expand().
# Accurate, hedged, research-framed. Each entry: slug, name (matches the members
# reference exactly so reconstitution auto-fills), sub, cls, evi/evicls, reg/regcls,
# ruo, what, mech (HTML), evidence (HTML), reg_html (HTML), refs, optional disc.
# eviCls: b-evi (early/preclinical, purple) | b-evi-trial (clinical/approved, blue)
# regCls: b-reg (RUO/investigational, amber) | b-reg-ok (approved, green)

RV = "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7287585/"        # peptide review
GHS = "https://onlinelibrary.wiley.com/doi/full/10.1002/rco2.9"      # GH secretagogues
GHREL = "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5412382/"      # ghrelin pathway
GPCR = "https://onlinelibrary.wiley.com/doi/abs/10.1002/anie.201302116"
HALF = "https://pubs.acs.org/doi/10.1021/acsmedchemlett.8b00226"
FDA503B = "https://www.fda.gov/news-events/press-announcements/fda-proposes-exclude-semaglutide-tirzepatide-and-liraglutide-503b-bulks-list"


def pm(term):
    return "https://pubmed.ncbi.nlm.nih.gov/?term=" + term.replace(" ", "+").replace("+", "%2B") if False else \
        "https://pubmed.ncbi.nlm.nih.gov/?term=" + term.replace(" ", "+")


def R(*items):
    """items: (label, cite, url) tuples -> numbered refs."""
    return [{"n": str(i + 1), "label": l, "cite": c, "url": u} for i, (l, c, u) in enumerate(items)]


RUO_STD = ("<b>Research Use Only.</b> Not an approved medicine and not for human use. "
           "Educational only — no dosing or medical advice.")
RUO_WADA = ("<b>Research Use Only.</b> Not FDA-approved; sold only as a research chemical. "
            "Many performance-adjacent peptides are also <b>WADA-prohibited</b> for tested athletes. "
            "Educational only — not medical advice.")
APPROVED = ("<b>Approved drug — used here for education.</b> This is an approved/prescription medicine in "
            "at least one region; \"research\"/compounded versions sold as chemicals are a separate, riskier thing. "
            "Not medical advice.")
INVEST = ("<b>Investigational.</b> In clinical development, <b>not approved</b>. Material sold as a research "
          "chemical is not the trial drug. Educational only — not medical advice.")

MORE = [
  # ── Metabolic / GLP & fat-loss research ────────────────────────────────
  dict(slug="5-amino-1mq", name="5-Amino-1MQ", cls="Metabolic research",
       sub="A small-molecule NNMT inhibitor studied in metabolism", evi="Evidence: preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="5-Amino-1MQ is a small molecule (not a peptide) studied as an inhibitor of the enzyme <strong>NNMT</strong> (nicotinamide N-methyltransferase), which is linked to fat-cell metabolism and cellular NAD⁺ handling.",
       mech="<p>By inhibiting NNMT, it is proposed in animal/cell models to raise cellular NAD⁺ and shift adipocyte energy metabolism toward fat breakdown.<sup><a href='#r1'>1</a></sup> This is a preclinical hypothesis, not a demonstrated human effect.</p>",
       evidence="<ul><li>Preclinical (rodent/cell) only; <strong>no human trials</strong> establishing efficacy or safety.</li></ul>",
       reg_html="<ul><li>Not FDA-approved; sold RUO.</li></ul>",
       refs=R(("NNMT inhibition & metabolism (literature).", "PubMed: 5-Amino-1MQ", pm("5-Amino-1MQ NNMT")))),
  dict(slug="adipotide", name="Adipotide", cls="Metabolic research",
       sub="A pro-apoptotic peptide targeting fat-tissue vasculature", evi="Evidence: preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="Adipotide (FTPP) is an experimental peptide designed to target the blood supply of white fat tissue.",
       mech="<p>It couples a peptide that homes to prohibitin on fat-tissue blood vessels with a pro-apoptotic sequence, aiming to prune the vasculature that feeds fat — reducing fat mass in animal models.<sup><a href='#r1'>1</a></sup> Notably, kidney effects were seen in primate studies, a key safety caveat.</p>",
       evidence="<ul><li>Animal (including primate) data; <strong>not established in humans</strong>; safety signals (renal) noted.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Adipotide / targeted fat-vasculature ablation (literature).", "PubMed: Adipotide", pm("Adipotide")))),
  dict(slug="aod-9604", name="AOD-9604", cls="Metabolic research",
       sub="A fragment of growth hormone (hGH 176-191) studied for fat metabolism", evi="Evidence: preclinical / early", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="AOD-9604 is a synthetic fragment of the C-terminus of human growth hormone (residues 176-191), studied for effects on fat metabolism without the full growth-promoting activity of GH.",
       mech="<p>It is proposed to stimulate lipolysis (fat breakdown) and inhibit lipogenesis in a GH-like way, but without raising IGF-1 or blood glucose in the manner of full GH.<sup><a href='#r1'>1</a></sup> Human efficacy data are weak.</p>",
       evidence="<ul><li>Some early human exposure; obesity trials did not show convincing benefit; <strong>no approval</strong>.</li></ul>",
       reg_html="<ul><li>Not FDA-approved; RUO. WADA considerations apply to GH-related compounds.</li></ul>",
       refs=R(("AOD-9604 / hGH fragment (literature).", "PubMed: AOD-9604", pm("AOD-9604")))),
  dict(slug="bam-15", name="BAM-15", cls="Metabolic research",
       sub="A mitochondrial uncoupler studied in metabolic research", evi="Evidence: preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="BAM-15 is a small-molecule <strong>mitochondrial uncoupler</strong> (not a peptide) studied as a potentially safer successor to older uncouplers like DNP.",
       mech="<p>Uncouplers dissipate the mitochondrial proton gradient so cells burn more fuel as heat rather than making ATP, increasing energy expenditure in animal models.<sup><a href='#r1'>1</a></sup> Uncoupling has a narrow safety margin historically.</p>",
       evidence="<ul><li>Preclinical; <strong>no human efficacy/safety trials</strong> establishing use.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Mitochondrial uncouplers in metabolism (literature).", "PubMed: BAM-15", pm("BAM-15 uncoupler")))),
  dict(slug="cagrilintide", name="Cagrilintide", cls="Metabolic research",
       sub="A long-acting amylin analog (weight-management research)", evi="Evidence: Phase 2/3 (as combo)", evicls="b-evi-trial",
       reg="Investigational", regcls="b-reg", ruo=INVEST,
       what="Cagrilintide is a long-acting <strong>amylin analog</strong> being developed for weight management, notably paired with semaglutide (as CagriSema).",
       mech="<p>Amylin is a pancreatic hormone that promotes satiety and slows gastric emptying; an amylin-receptor agonist adds a satiety pathway complementary to <a href='semaglutide.html'>GLP-1</a>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Clinical development (with strong combination data for CagriSema); <strong>not yet approved</strong> as a standalone.</li></ul>",
       reg_html="<ul><li>Investigational; not approved.</li></ul>",
       refs=R(("Amylin analogs in obesity (literature).", "PubMed: cagrilintide", pm("cagrilintide")))),
  dict(slug="mazdutide", name="Mazdutide", cls="Metabolic research",
       sub="A GLP-1 / glucagon dual receptor agonist (investigational)", evi="Evidence: Phase 3 (ongoing)", evicls="b-evi-trial",
       reg="Investigational", regcls="b-reg", ruo=INVEST,
       what="Mazdutide is a dual <strong>GLP-1 / glucagon</strong> receptor agonist in clinical development for diabetes and obesity.",
       mech="<p>It combines GLP-1 agonism (satiety, glucose control) with glucagon-receptor agonism (energy expenditure) — the same twin-pathway logic behind <a href='retatrutide.html'>retatrutide</a>, minus the GIP arm.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Phase 3 development, strongest in China; <strong>not FDA-approved</strong>.</li></ul>",
       reg_html="<ul><li>Investigational; approval status varies by region.</li></ul>",
       refs=R(("Dual GLP-1/glucagon agonists (literature).", "PubMed: mazdutide", pm("mazdutide")))),
  dict(slug="orforglipron", name="Orforglipron", cls="Metabolic research",
       sub="An oral, non-peptide small-molecule GLP-1 receptor agonist", evi="Evidence: Phase 3 (ongoing)", evicls="b-evi-trial",
       reg="Investigational", regcls="b-reg", ruo=INVEST,
       what="Orforglipron is an <strong>oral, small-molecule</strong> GLP-1 receptor agonist — notable because it is not a peptide and does not require injection or the special formulation oral semaglutide needs.",
       mech="<p>It activates the same GLP-1 receptor (a class B GPCR) as injectable GLP-1 drugs, but as a small molecule it can be taken as a simple pill.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Phase 3 program underway with strong Phase 2 data; <strong>not yet approved</strong>.</li></ul>",
       reg_html="<ul><li>Investigational; not approved.</li></ul>",
       refs=R(("Oral small-molecule GLP-1 agonists (literature).", "PubMed: orforglipron", pm("orforglipron")))),
  dict(slug="survodutide", name="Survodutide", cls="Metabolic research",
       sub="A GLP-1 / glucagon dual agonist (investigational)", evi="Evidence: Phase 2/3", evicls="b-evi-trial",
       reg="Investigational", regcls="b-reg", ruo=INVEST,
       what="Survodutide is a dual <strong>GLP-1 / glucagon</strong> receptor agonist studied in obesity and, notably, MASH (fatty liver disease).",
       mech="<p>Like mazdutide, it pairs GLP-1 agonism with glucagon-receptor agonism; the glucagon arm is of particular interest for liver-fat reduction.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Positive Phase 2 (incl. MASH); Phase 3 ongoing; <strong>not approved</strong>.</li></ul>",
       reg_html="<ul><li>Investigational; not approved.</li></ul>",
       refs=R(("GLP-1/glucagon dual agonists in MASH/obesity (literature).", "PubMed: survodutide", pm("survodutide")))),
  dict(slug="slu-pp-332", name="SLU-PP-332", cls="Metabolic research",
       sub="An ERRα agonist studied as an exercise-mimetic", evi="Evidence: preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="SLU-PP-332 is a small molecule (not a peptide) studied as an agonist of the <strong>estrogen-related receptor α (ERRα)</strong>, marketed in research circles as an \"exercise mimetic.\"",
       mech="<p>ERRα regulates mitochondrial and oxidative-metabolism genes; agonizing it is proposed to increase fat oxidation and endurance in rodents without exercise.<sup><a href='#r1'>1</a></sup> This is preclinical.</p>",
       evidence="<ul><li>Rodent data only; <strong>no human trials</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("ERRα agonism / exercise-mimetic research.", "PubMed: SLU-PP-332", pm("SLU-PP-332")))),
  dict(slug="tesofensine", name="Tesofensine", cls="Metabolic research",
       sub="A triple monoamine-reuptake inhibitor studied for weight loss", evi="Evidence: Phase 2 (Phase 3 pending)", evicls="b-evi-trial",
       reg="Investigational", regcls="b-reg", ruo=INVEST,
       what="Tesofensine is a small-molecule <strong>serotonin-noradrenaline-dopamine reuptake inhibitor</strong> (not a peptide) studied for obesity.",
       mech="<p>By raising three neurotransmitters, it suppresses appetite centrally.<sup><a href='#r1'>1</a></sup> As a CNS stimulant-type mechanism, cardiovascular and psychiatric effects are the key safety questions.</p>",
       evidence="<ul><li>Phase 2 showed notable weight loss; <strong>not FDA-approved</strong>.</li></ul>",
       reg_html="<ul><li>Investigational; not approved.</li></ul>",
       refs=R(("Tesofensine in obesity (literature).", "PubMed: tesofensine", pm("tesofensine")))),
  dict(slug="l-carnitine", name="L-Carnitine", cls="Metabolic research",
       sub="An amino-acid derivative in fatty-acid transport", evi="Evidence: mixed human", evicls="b-evi",
       reg="Supplement / approved (deficiency)", regcls="b-reg-ok", ruo=APPROVED,
       what="L-Carnitine is a naturally occurring amino-acid derivative (not a peptide) essential for transporting fatty acids into mitochondria to be burned for energy.",
       mech="<p>It shuttles long-chain fatty acids across the mitochondrial membrane (the carnitine shuttle). Whether supplementation enhances fat loss in people with normal carnitine levels is <strong>not well supported</strong>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Established for genuine carnitine deficiency; performance/fat-loss claims in healthy people are mixed.</li></ul>",
       reg_html="<ul><li>Available as a supplement; a prescription form exists for deficiency.</li></ul>",
       refs=R(("L-carnitine metabolism & supplementation (literature).", "PubMed: L-carnitine", pm("L-carnitine supplementation"))), disc="L-Carnitine is a dietary supplement / prescription for deficiency; not a treatment claim."),

  # ── GH secretagogues ───────────────────────────────────────────────────
  dict(slug="ipamorelin", name="Ipamorelin", cls="GH secretagogue",
       sub="A selective ghrelin-receptor (GHS-R) agonist", evi="Evidence: preclinical / early", evicls="b-evi",
       reg="RUO · WADA-prohibited", regcls="b-reg", ruo=RUO_WADA,
       what="Ipamorelin is a selective <strong>ghrelin-receptor (GHS-R) agonist</strong> — a growth-hormone secretagogue often paired with a GHRH analog (see <a href='cjc-1295-ipamorelin.html'>CJC-1295 + Ipamorelin</a>).",
       mech="<p>Activating GHS-R triggers a pulse of growth-hormone release; ipamorelin is valued in research for being relatively selective (little effect on cortisol/prolactin).<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Preclinical/early; <strong>not an approved therapy</strong>.</li></ul>",
       reg_html="<ul><li>RUO; GH secretagogues are WADA-prohibited (S2).</li></ul>",
       refs=R(("Ghrelin / GHS-R pathway (review).", "PMC5412382", GHREL), ("GH secretagogues (review).", "rco2.9", GHS))),
  dict(slug="ghrp-2", name="GHRP-2", cls="GH secretagogue",
       sub="A growth-hormone-releasing peptide (ghrelin mimetic)", evi="Evidence: early human PK", evicls="b-evi",
       reg="RUO · WADA-prohibited", regcls="b-reg", ruo=RUO_WADA,
       what="GHRP-2 is a growth-hormone-releasing peptide that acts as a ghrelin-receptor agonist.",
       mech="<p>Like other GHRPs it stimulates GH release via GHS-R; it can also modestly raise cortisol/prolactin/appetite — less selective than ipamorelin.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Early human PK exists; <strong>not an approved therapy</strong>.</li></ul>",
       reg_html="<ul><li>RUO; WADA-prohibited (S2).</li></ul>",
       refs=R(("Ghrelin / GHS-R pathway (review).", "PMC5412382", GHREL))),
  dict(slug="ghrp-6", name="GHRP-6", cls="GH secretagogue",
       sub="A growth-hormone-releasing peptide (strong appetite effect)", evi="Evidence: early human PK", evicls="b-evi",
       reg="RUO · WADA-prohibited", regcls="b-reg", ruo=RUO_WADA,
       what="GHRP-6 is one of the original growth-hormone-releasing peptides, a ghrelin-receptor agonist notable for a pronounced hunger effect.",
       mech="<p>Stimulates a GH pulse via GHS-R and strongly increases appetite (ghrelin is the \"hunger hormone\").<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Early human data; <strong>not approved</strong>.</li></ul>",
       reg_html="<ul><li>RUO; WADA-prohibited (S2).</li></ul>",
       refs=R(("Ghrelin / GHS-R pathway (review).", "PMC5412382", GHREL))),
  dict(slug="mk-677", name="MK-677 (Oral 25 mg)", cls="GH secretagogue",
       sub="Ibutamoren — an orally-active ghrelin-receptor agonist", evi="Evidence: human trials (not approved)", evicls="b-evi-trial",
       reg="RUO · WADA-prohibited", regcls="b-reg", ruo=RUO_WADA,
       what="MK-677 (ibutamoren) is an <strong>orally active, long-acting</strong> ghrelin-receptor agonist — unusual for being a non-peptide small molecule that raises GH/IGF-1.",
       mech="<p>Sustained GHS-R agonism raises GH and IGF-1 around the clock; because it's oral and long-acting it behaves differently from injectable pulsatile GHRPs.<sup><a href='#r1'>1</a></sup> Water retention and insulin-sensitivity effects are noted.</p>",
       evidence="<ul><li>Studied in humans (e.g., for body composition, sleep) but <strong>never FDA-approved</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; RUO. WADA-prohibited (S2).</li></ul>",
       refs=R(("GH secretagogues incl. ibutamoren (review).", "rco2.9", GHS), ("Ghrelin pathway (review).", "PMC5412382", GHREL))),
  dict(slug="sermorelin", name="Sermorelin Acetate", cls="GH secretagogue",
       sub="A GHRH(1-29) analog", evi="Evidence: was FDA-approved (diagnostic)", evicls="b-evi-trial",
       reg="Approval withdrawn · now RUO/compounded", regcls="b-reg", ruo=APPROVED,
       what="Sermorelin is a synthetic fragment of GHRH (the first 29 amino acids) — historically an approved diagnostic for GH function.",
       mech="<p>As a GHRH-receptor agonist it prompts the pituitary to release GH in a physiological, pulsatile way.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Had FDA approval (Geref) that was later withdrawn from the market; now seen mainly compounded/RUO. Approval history is a useful teaching contrast with RUO peptides.</li></ul>",
       reg_html="<ul><li>Original approval discontinued; current supply is compounded/RUO. WADA-prohibited (S2).</li></ul>",
       refs=R(("GHRH analogs / secretagogues (review).", "rco2.9", GHS))),

  # ── Healing / immune ───────────────────────────────────────────────────
  dict(slug="bpc-157-oral", name="BPC-157 (Oral)", cls="Healing & repair",
       sub="Oral form of the gastric pentadecapeptide", evi="Evidence: preclinical", evicls="b-evi",
       reg="RUO · WADA-prohibited", regcls="b-reg", ruo=RUO_WADA,
       what="An oral presentation of <a href='bpc-157.html'>BPC-157</a>, leveraging its reported stability in gastric acid. See the full <a href='bpc-157.html'>BPC-157 profile</a> for mechanism and evidence.",
       mech="<p>Same proposed mechanisms as injectable BPC-157 (angiogenesis via VEGFR2, NO modulation); oral absorption and systemic exposure in humans are not well characterized.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Preclinical; <strong>no Phase III</strong>. Human oral bioavailability uncertain.</li></ul>",
       reg_html="<ul><li>RUO; WADA-prohibited.</li></ul>",
       refs=R(("BPC-157 background (literature).", "globalrph.com", "https://globalrph.com/2025/11/bpc-157-and-tb-500-background-indications-efficacy-and-safety/"))),
  dict(slug="kpv", name="KPV", cls="Immune / healing",
       sub="A C-terminal α-MSH tripeptide with anti-inflammatory research", evi="Evidence: preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="KPV is a tripeptide (lysine-proline-valine) corresponding to the C-terminus of α-MSH, studied for anti-inflammatory effects, especially in gut models.",
       mech="<p>It is reported to reduce inflammatory signaling (e.g., NF-κB pathway) in intestinal and skin models, without the pigmentation effects of full α-MSH.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Preclinical anti-inflammatory data; <strong>no Phase III</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("KPV / α-MSH anti-inflammatory peptides (literature).", "PubMed: KPV peptide", pm("KPV peptide anti-inflammatory")))),
  dict(slug="kpv-oral", name="KPV (Oral 500 mcg)", cls="Immune / healing",
       sub="Oral form of the α-MSH tripeptide", evi="Evidence: preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="An oral presentation of <a href='kpv.html'>KPV</a>, studied for gut-directed anti-inflammatory effects. See the <a href='kpv.html'>KPV profile</a>.",
       mech="<p>Same proposed anti-inflammatory mechanism as KPV; oral/local delivery to the gut is the rationale.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Preclinical; <strong>no Phase III</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("KPV anti-inflammatory peptides (literature).", "PubMed: KPV peptide", pm("KPV peptide")))),
  dict(slug="ll-37", name="LL-37", cls="Immune / healing",
       sub="A human cathelicidin antimicrobial peptide", evi="Evidence: preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="LL-37 is the only human <strong>cathelicidin</strong> antimicrobial peptide, part of innate immunity, studied for antimicrobial, wound-healing and immunomodulatory roles.",
       mech="<p>It disrupts microbial membranes and modulates immune signaling and angiogenesis; context-dependent (can be pro- or anti-inflammatory).<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Substantial basic-science literature; human therapeutic use is <strong>not established</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Cathelicidin LL-37 in immunity (review).", "PMC7287585", RV))),
  dict(slug="vip", name="VIP (Vasoactive Intestinal Peptide)", cls="Immune / healing",
       sub="A 28-aa neuropeptide with broad immune/vascular roles", evi="Evidence: preclinical / niche clinical", evicls="b-evi",
       reg="RUO (research); niche approved uses", regcls="b-reg", ruo=RUO_STD,
       what="VIP is a naturally occurring 28-amino-acid neuropeptide with wide roles in the gut, lungs, immune system and circadian signaling.",
       mech="<p>It signals through VPAC receptors (GPCRs), producing vasodilation, smooth-muscle relaxation and immunomodulation.<sup><a href='#r1'>1</a></sup> It is studied in inflammatory conditions.</p>",
       evidence="<ul><li>Rich basic science; broad research-chemical use is <strong>not an approved therapy</strong>.</li></ul>",
       reg_html="<ul><li>Sold RUO for research; not an approved general therapy.</li></ul>",
       refs=R(("VIP / VPAC signalling (review).", "PMC7287585", RV))),
  dict(slug="thymosin-alpha-1", name="Thymosin Alpha-1", cls="Immune / healing",
       sub="An immune-modulating peptide (Tα1)", evi="Evidence: approved in some regions", evicls="b-evi-trial",
       reg="Approved in some countries · RUO in US", regcls="b-reg", ruo=APPROVED,
       what="Thymosin alpha-1 (Tα1) is a 28-amino-acid immune-modulating peptide derived from the thymus.",
       mech="<p>It enhances T-cell and dendritic-cell function and modulates innate immunity — studied in infections, sepsis and as a vaccine adjuvant.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Approved/marketed (as Zadaxin) in a number of countries for certain infections; <strong>not FDA-approved</strong> in the US, where it is sold RUO.</li></ul>",
       reg_html="<ul><li>Approval varies by region; RUO in the US.</li></ul>",
       refs=R(("Thymosin alpha-1 immunomodulation (literature).", "PubMed: thymosin alpha-1", pm("thymosin alpha 1 immune")))),
  dict(slug="ara-290", name="ARA-290", cls="Healing & repair",
       sub="Cibinetide — an erythropoietin-derived tissue-protective peptide", evi="Evidence: early clinical", evicls="b-evi-trial",
       reg="Investigational", regcls="b-reg", ruo=INVEST,
       what="ARA-290 (cibinetide) is a small peptide derived from erythropoietin, engineered to keep EPO's tissue-protective effects <em>without</em> raising red blood cells.",
       mech="<p>It activates the \"innate repair receptor\" (an EPOR/β-common-receptor complex) to reduce inflammation and support nerve/tissue repair — studied in neuropathic pain (e.g., sarcoidosis).<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Early-phase human trials (neuropathic pain); <strong>not approved</strong>.</li></ul>",
       reg_html="<ul><li>Investigational; not approved.</li></ul>",
       refs=R(("ARA-290 / cibinetide trials (literature).", "PubMed: ARA-290 cibinetide", pm("ARA-290 cibinetide")))),

  # ── Cognitive / neuro ──────────────────────────────────────────────────
  dict(slug="semax", name="Semax", cls="Cognitive research",
       sub="A synthetic ACTH(4-10) analog (Russian nootropic)", evi="Evidence: mostly Russian clinical", evicls="b-evi",
       reg="Approved in Russia · RUO elsewhere", regcls="b-reg", ruo=APPROVED,
       what="Semax is a synthetic peptide analog of a fragment of ACTH (4-10), developed in Russia as a nootropic/neuroprotective agent.",
       mech="<p>It is reported to modulate BDNF and other neurotrophic signaling and dopaminergic/serotonergic systems, without ACTH's hormonal effects.<sup><a href='#r1'>1</a></sup> Most evidence is Russian and not widely replicated.</p>",
       evidence="<ul><li>Clinical use/approval in Russia; <strong>little independent Western trial data</strong>; RUO elsewhere.</li></ul>",
       reg_html="<ul><li>Approved in Russia; RUO in the US/EU.</li></ul>",
       refs=R(("Semax / ACTH-fragment nootropics (literature).", "PubMed: Semax", pm("Semax peptide")))),
  dict(slug="selank", name="Selank", cls="Cognitive research",
       sub="A synthetic tuftsin analog (anxiolytic research)", evi="Evidence: mostly Russian clinical", evicls="b-evi",
       reg="Approved in Russia · RUO elsewhere", regcls="b-reg", ruo=APPROVED,
       what="Selank is a synthetic peptide based on the immunomodulatory peptide tuftsin, developed in Russia as an anxiolytic/nootropic.",
       mech="<p>It is reported to modulate GABAergic and monoamine systems and BDNF, and to influence enkephalin metabolism, producing anxiolytic effects in animal models.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Russian clinical use; <strong>limited independent trials</strong>; RUO elsewhere.</li></ul>",
       reg_html="<ul><li>Approved in Russia; RUO in the US/EU.</li></ul>",
       refs=R(("Selank / tuftsin anxiolytic peptides (literature).", "PubMed: Selank", pm("Selank peptide")))),
  dict(slug="cerebrolysin", name="Cerebrolysin", cls="Cognitive research",
       sub="A porcine-brain-derived peptide preparation (neurotrophic)", evi="Evidence: clinical (mixed)", evicls="b-evi-trial",
       reg="Approved in some countries · not US", regcls="b-reg", ruo=APPROVED,
       what="Cerebrolysin is a mixture of low-molecular-weight peptides and amino acids derived from porcine brain, used in some countries for stroke and dementia.",
       mech="<p>It is proposed to have neurotrophic, neuroprotective effects mimicking endogenous growth factors.<sup><a href='#r1'>1</a></sup> Trial results are mixed and debated.</p>",
       evidence="<ul><li>Marketed in numerous countries; efficacy evidence is <strong>mixed/contested</strong>; <strong>not FDA-approved</strong>.</li></ul>",
       reg_html="<ul><li>Approval varies by region; not FDA-approved.</li></ul>",
       refs=R(("Cerebrolysin trials (literature).", "PubMed: cerebrolysin", pm("cerebrolysin stroke dementia")))),
  dict(slug="dsip", name="DSIP", cls="Sleep research",
       sub="Delta sleep-inducing peptide", evi="Evidence: preclinical / inconsistent", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="DSIP (delta sleep-inducing peptide) is a naturally occurring nonapeptide first isolated from sleep-related brain activity.",
       mech="<p>Its precise mechanism and receptor are <strong>not clearly defined</strong>; effects on sleep architecture, stress hormones and pain have been reported inconsistently.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Old and inconsistent literature; <strong>no approved use</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("DSIP research (literature).", "PubMed: delta sleep inducing peptide", pm("delta sleep inducing peptide")))),

  # ── Longevity / cellular ───────────────────────────────────────────────
  dict(slug="epitalon", name="Epitalon", cls="Longevity & cellular",
       sub="A synthetic tetrapeptide bioregulator (Ala-Glu-Asp-Gly)", evi="Evidence: mostly Russian preclinical/clinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="Epitalon (epithalon) is a synthetic tetrapeptide based on epithalamin, a pineal-gland extract; a Khavinson \"peptide bioregulator\" studied for aging.",
       mech="<p>It is claimed in Russian research to influence telomerase activity and circadian/melatonin regulation.<sup><a href='#r1'>1</a></sup> Independent human replication is limited.</p>",
       evidence="<ul><li>Primarily Russian preclinical/small clinical work; <strong>not independently established</strong>; no approval.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Epitalon / pineal peptides (literature).", "PubMed: epitalon", pm("epitalon epithalon telomerase")))),
  dict(slug="ss-31", name="SS-31", cls="Longevity & cellular",
       sub="Elamipretide — a mitochondria-targeting tetrapeptide", evi="Evidence: clinical (mixed)", evicls="b-evi-trial",
       reg="Investigational", regcls="b-reg", ruo=INVEST,
       what="SS-31 (elamipretide) is a mitochondria-targeting tetrapeptide that concentrates on the inner mitochondrial membrane.",
       mech="<p>It binds <strong>cardiolipin</strong> on the inner mitochondrial membrane, stabilizing the machinery of energy production and reducing harmful reactive-oxygen production.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Multiple human trials (mitochondrial disease, heart failure) with <strong>mixed results</strong>; <strong>not approved</strong>.</li></ul>",
       reg_html="<ul><li>Investigational; not approved.</li></ul>",
       refs=R(("Elamipretide / cardiolipin-targeting peptide (literature).", "PubMed: elamipretide SS-31", pm("elamipretide SS-31")))),
  dict(slug="igf1-lr3", name="IGF1-LR3", cls="Growth & cellular",
       sub="A long-acting analog of insulin-like growth factor 1", evi="Evidence: preclinical", evicls="b-evi",
       reg="RUO · WADA-prohibited", regcls="b-reg", ruo=RUO_WADA,
       what="IGF-1 LR3 (Long R3 IGF-1) is an engineered, longer-acting analog of insulin-like growth factor 1, used mainly as a cell-culture reagent.",
       mech="<p>It activates the IGF-1 receptor to drive cell growth/proliferation; the LR3 modifications reduce binding to IGF-binding proteins, extending its activity.<sup><a href='#r1'>1</a></sup> Growth-factor signaling carries theoretical proliferation risks.</p>",
       evidence="<ul><li>Lab reagent; <strong>no human therapeutic evidence</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; RUO. WADA-prohibited (S2).</li></ul>",
       refs=R(("IGF-1 signalling (review).", "PMC7287585", RV))),
  dict(slug="l-glutathione", name="L-Glutathione", cls="Antioxidant research",
       sub="The body's principal intracellular antioxidant (a tripeptide)", evi="Evidence: mixed human", evicls="b-evi",
       reg="Supplement / RUO (injectable)", regcls="b-reg", ruo=RUO_STD,
       what="Glutathione is a naturally occurring <strong>tripeptide</strong> (glutamate-cysteine-glycine) — the cell's main antioxidant and a key detox cofactor.",
       mech="<p>It neutralizes reactive oxygen species and participates in phase-II detoxification via glutathione-S-transferases.<sup><a href='#r1'>1</a></sup> Oral bioavailability is poor; IV/injectable use is common in wellness settings but evidence for systemic benefit is limited.</p>",
       evidence="<ul><li>Central endogenous antioxidant; supplementation benefits in healthy people are <strong>mixed</strong>.</li></ul>",
       reg_html="<ul><li>Oral forms sold as supplements; injectable use is off-label/RUO.</li></ul>",
       refs=R(("Glutathione antioxidant biology (literature).", "PubMed: glutathione supplementation", pm("glutathione supplementation antioxidant")))),

  # ── Cosmetic / skin ────────────────────────────────────────────────────
  dict(slug="ahk-cu", name="AHK-Cu", cls="Skin & cosmetic",
       sub="A copper-binding tripeptide (hair/skin research)", evi="Evidence: cosmetic/preclinical", evicls="b-evi",
       reg="Topical cosmetic · injectable RUO", regcls="b-reg", ruo=RUO_STD,
       what="AHK-Cu is a copper-binding tripeptide (alanine-histidine-lysine + Cu) related to <a href='ghk-cu.html'>GHK-Cu</a>, studied mainly for hair-follicle and skin effects in cosmetics.",
       mech="<p>Like other copper peptides it is proposed to support angiogenesis and growth-factor signaling around hair follicles; most data are topical/cosmetic.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Cosmetic/preclinical; systemic human data minimal.</li></ul>",
       reg_html="<ul><li>Topical cosmetic use; injectable is RUO.</li></ul>",
       refs=R(("Copper peptides in skin/hair (literature).", "PubMed: copper peptide hair", pm("copper peptide hair AHK")))),
  dict(slug="melanotan-2", name="Melanotan II", cls="Skin & cosmetic",
       sub="A melanocortin-receptor agonist (tanning research)", evi="Evidence: preclinical / anecdotal", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="Melanotan II is a synthetic analog of α-MSH that activates melanocortin receptors, marketed for skin pigmentation/tanning and libido effects.",
       mech="<p>It agonizes melanocortin receptors (MC1R → pigmentation; MC4R → appetite/sexual pathways, the basis of the related drug <a href='pt-141.html'>PT-141</a>).<sup><a href='#r1'>1</a></sup> Broad receptor activity means broad side effects (nausea, moles, blood-pressure changes).</p>",
       evidence="<ul><li>Not approved; safety concerns (unregulated tanning use); <strong>no approval</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; RUO. Public-health warnings exist about unregulated use.</li></ul>",
       refs=R(("Melanocortin agonists (literature).", "PubMed: melanotan", pm("melanotan II melanocortin")))),
  dict(slug="snap-8", name="Snap-8", cls="Skin & cosmetic",
       sub="An octapeptide 'topical Botox-like' cosmetic ingredient", evi="Evidence: cosmetic/topical", evicls="b-evi",
       reg="Topical cosmetic", regcls="b-reg", ruo=RUO_STD,
       what="Snap-8 (acetyl octapeptide-3) is a cosmetic peptide marketed as a topical alternative to neuromodulators for expression lines.",
       mech="<p>It is proposed to interfere with the SNARE complex involved in neurotransmitter release at the neuromuscular junction, mildly reducing muscle contraction — a topical, far weaker analogy to botulinum toxin.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Cosmetic/topical marketing data; not a drug.</li></ul>",
       reg_html="<ul><li>Used as a topical cosmetic ingredient.</li></ul>",
       refs=R(("Cosmetic peptides / SNARE-modulating peptides (literature).", "PubMed: acetyl octapeptide", pm("acetyl octapeptide-3 cosmetic")))),
  dict(slug="lemon-bottle", name="Lemon Bottle", cls="Cosmetic research",
       sub="A proprietary lipolytic injection blend", evi="Evidence: none peer-reviewed", evicls="b-evi",
       reg="Not approved · RUO/cosmetic", regcls="b-reg", ruo=RUO_STD,
       what="Lemon Bottle is a proprietary \"fat-dissolving\" injection blend (commonly listing ingredients like riboflavin, lecithin/phosphatidylcholine and others) marketed for localized fat reduction.",
       mech="<p>Proprietary blends of this type are proposed to emulsify/disrupt fat-cell membranes locally.<sup><a href='#r1'>1</a></sup> Formulations vary and are not standardized.</p>",
       evidence="<ul><li><strong>No robust peer-reviewed evidence</strong>; not an approved product; safety/regulatory warnings exist in several countries.</li></ul>",
       reg_html="<ul><li>Not approved; unregulated cosmetic injectable.</li></ul>",
       refs=R(("Injectable lipolysis / phosphatidylcholine (literature).", "PubMed: injection lipolysis", pm("injection lipolysis phosphatidylcholine")))),

  # ── Hormonal ───────────────────────────────────────────────────────────
  dict(slug="hcg", name="hCG", cls="Hormonal research",
       sub="Human chorionic gonadotropin (LH-mimetic)", evi="Evidence: FDA-approved (specific uses)", evicls="b-evi-trial",
       reg="FDA-approved (specific indications)", regcls="b-reg-ok", ruo=APPROVED,
       what="hCG (human chorionic gonadotropin) is a naturally occurring glycoprotein hormone that mimics luteinizing hormone (LH).",
       mech="<p>It stimulates gonadal function — in males, testicular testosterone production; used in fertility and certain endocrine settings.<sup><a href='#r1'>1</a></sup> (The \"hCG diet\" for weight loss is <strong>not supported</strong> and the FDA has warned against it.)</p>",
       evidence="<ul><li>Approved for specific fertility/endocrine indications; weight-loss claims are <strong>disproven</strong>.</li></ul>",
       reg_html="<ul><li>FDA-approved (prescription) for defined indications; weight-loss use warned against.</li></ul>",
       refs=R(("hCG clinical pharmacology (literature).", "PubMed: hCG", pm("human chorionic gonadotropin therapy"))), disc="hCG is a prescription drug; obtain and use medicines only under a licensed professional."),
  dict(slug="kisspeptin", name="Kisspeptin", cls="Hormonal research",
       sub="A hypothalamic peptide upstream of reproductive hormones", evi="Evidence: early clinical", evicls="b-evi-trial",
       reg="Investigational", regcls="b-reg", ruo=INVEST,
       what="Kisspeptin is a naturally occurring hypothalamic peptide that sits at the top of the reproductive-hormone axis.",
       mech="<p>It stimulates GnRH neurons, driving downstream LH/FSH and sex-hormone release; studied in fertility and hypothalamic conditions.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Active human research (fertility, sexual function); <strong>not an approved therapy</strong>.</li></ul>",
       reg_html="<ul><li>Investigational; not approved.</li></ul>",
       refs=R(("Kisspeptin & the reproductive axis (literature).", "PubMed: kisspeptin", pm("kisspeptin reproductive")))),
  dict(slug="oxytocin", name="Oxytocin", cls="Hormonal research",
       sub="A naturally occurring nonapeptide hormone", evi="Evidence: FDA-approved (obstetric)", evicls="b-evi-trial",
       reg="FDA-approved (specific uses)", regcls="b-reg-ok", ruo=APPROVED,
       what="Oxytocin is a naturally occurring nine-amino-acid hormone/neuropeptide, well known in childbirth and lactation and studied in social behavior.",
       mech="<p>It acts on oxytocin receptors (GPCRs) to cause uterine contraction and milk let-down, and centrally influences social/affiliative behavior.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Approved (injectable) for obstetric use; behavioral/wellness uses are <strong>research-stage</strong>.</li></ul>",
       reg_html="<ul><li>FDA-approved for obstetric indications; other uses off-label/research.</li></ul>",
       refs=R(("Oxytocin physiology & behavior (literature).", "PubMed: oxytocin", pm("oxytocin behavior physiology"))), disc="Oxytocin is a prescription drug; obtain and use medicines only under a licensed professional."),

  # ── Mitochondrial / other small molecules ──────────────────────────────
  dict(slug="methylene-blue", name="Methylene Blue (Oral 25 mg)", cls="Mitochondrial research",
       sub="A century-old dye & redox agent (FDA-approved for methemoglobinemia)", evi="Evidence: approved (specific) + emerging", evicls="b-evi-trial",
       reg="FDA-approved (specific indication)", regcls="b-reg-ok", ruo=APPROVED,
       what="Methylene blue is a synthetic dye (not a peptide) and one of the oldest drugs — FDA-approved to treat methemoglobinemia, and studied at low doses for mitochondrial/cognitive effects.",
       mech="<p>At low doses it acts as an alternative electron carrier in the mitochondrial electron-transport chain and has antioxidant/redox effects; it is also a potent MAO inhibitor (a key drug-interaction caution).<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Approved for methemoglobinemia; cognitive/longevity uses are <strong>emerging/unproven</strong>.</li></ul>",
       reg_html="<ul><li>FDA-approved for a specific indication; other uses off-label. Serotonergic drug interactions are dangerous.</li></ul>",
       refs=R(("Methylene blue pharmacology (literature).", "PubMed: methylene blue", pm("methylene blue mitochondria cognition"))), disc="Methylene blue is a drug with serious interactions; use only under a licensed professional."),
  dict(slug="vitamin-b12", name="Vitamin B12", cls="Vitamin support",
       sub="Cobalamin — an essential vitamin", evi="Evidence: established (deficiency)", evicls="b-evi-trial",
       reg="Supplement / approved (deficiency)", regcls="b-reg-ok", ruo=APPROVED,
       what="Vitamin B12 (cobalamin) is an essential vitamin (not a peptide) required for red-blood-cell formation, neurological function and DNA synthesis.",
       mech="<p>It is a cofactor for enzymes in methylation and fatty-acid/amino-acid metabolism; deficiency causes anemia and neuropathy.<sup><a href='#r1'>1</a></sup> Extra B12 in replete people does not add energy.</p>",
       evidence="<ul><li>Clearly beneficial in deficiency; <strong>no benefit</strong> from megadoses in replete people.</li></ul>",
       reg_html="<ul><li>Available as supplement; injectable used medically for deficiency.</li></ul>",
       refs=R(("Vitamin B12 physiology (literature).", "PubMed: vitamin B12", pm("vitamin B12 deficiency"))), disc="Vitamin B12 is a supplement/medical treatment for deficiency; not a general energy therapy."),

  # ── Peptide bioregulators (Khavinson short peptides) ───────────────────
  dict(slug="bronchogen", name="Bronchogen", cls="Peptide bioregulator",
       sub="A short 'bioregulator' peptide (lung tissue)", evi="Evidence: Russian preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="Bronchogen is a short synthetic \"peptide bioregulator\" (Khavinson-type) marketed toward respiratory/lung tissue.",
       mech="<p>These very short peptides are hypothesized in Russian research to bind DNA and tissue-selectively influence gene expression (\"peptide bioregulation\").<sup><a href='#r1'>1</a></sup> The mechanism is <strong>not independently established</strong>.</p>",
       evidence="<ul><li>Primarily Russian preclinical work; <strong>little independent human data</strong>; no approval.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Peptide bioregulators / short-peptide research.", "PubMed: peptide bioregulator Khavinson", pm("Khavinson peptide bioregulator")))),
  dict(slug="cardiogen", name="Cardiogen", cls="Peptide bioregulator",
       sub="A short 'bioregulator' peptide (heart tissue)", evi="Evidence: Russian preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="Cardiogen is a short synthetic peptide bioregulator marketed toward cardiovascular tissue.",
       mech="<p>Proposed, like other Khavinson peptides, to tissue-selectively influence gene expression; <strong>not independently established</strong>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Russian preclinical; <strong>little independent data</strong>; no approval.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Peptide bioregulators (literature).", "PubMed: Khavinson peptide", pm("Khavinson peptide bioregulator")))),
  dict(slug="cartalax", name="Cartalax", cls="Peptide bioregulator",
       sub="A short 'bioregulator' tripeptide (cartilage/connective)", evi="Evidence: Russian preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="Cartalax is a short synthetic peptide bioregulator marketed toward cartilage/connective tissue.",
       mech="<p>Same proposed \"peptide bioregulation\" hypothesis as other Khavinson peptides; <strong>not independently established</strong>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Russian preclinical; no approval.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Peptide bioregulators (literature).", "PubMed: Khavinson peptide", pm("Khavinson peptide bioregulator")))),
  dict(slug="crystagen", name="Crystagen", cls="Peptide bioregulator",
       sub="A short 'bioregulator' peptide (immune)", evi="Evidence: Russian preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="Crystagen is a short synthetic peptide bioregulator marketed toward immune tissue.",
       mech="<p>Proposed tissue-selective gene-expression effects (Khavinson hypothesis); <strong>not independently established</strong>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Russian preclinical; no approval.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Peptide bioregulators (literature).", "PubMed: Khavinson peptide", pm("Khavinson peptide bioregulator")))),
  dict(slug="pancragen", name="Pancragen", cls="Peptide bioregulator",
       sub="A short 'bioregulator' peptide (pancreas)", evi="Evidence: Russian preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="Pancragen is a short synthetic peptide bioregulator marketed toward pancreatic tissue.",
       mech="<p>Proposed tissue-selective bioregulation (Khavinson hypothesis); <strong>not independently established</strong>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Russian preclinical; no approval.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Peptide bioregulators (literature).", "PubMed: Khavinson peptide", pm("Khavinson peptide bioregulator")))),
  dict(slug="pinealon", name="Pinealon", cls="Peptide bioregulator",
       sub="A short 'bioregulator' tripeptide (brain/pineal)", evi="Evidence: Russian preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="Pinealon is a short synthetic peptide bioregulator marketed toward brain/CNS tissue.",
       mech="<p>Proposed neuro-directed bioregulation (Khavinson hypothesis); <strong>not independently established</strong>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Russian preclinical; no approval.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Peptide bioregulators (literature).", "PubMed: Khavinson peptide", pm("Khavinson peptide bioregulator")))),
  dict(slug="prostamax", name="Prostamax", cls="Peptide bioregulator",
       sub="A short 'bioregulator' peptide (prostate)", evi="Evidence: Russian preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="Prostamax is a short synthetic peptide bioregulator marketed toward prostate tissue.",
       mech="<p>Proposed tissue-selective bioregulation (Khavinson hypothesis); <strong>not independently established</strong>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Russian preclinical; no approval.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Peptide bioregulators (literature).", "PubMed: Khavinson peptide", pm("Khavinson peptide bioregulator")))),
  dict(slug="vilon", name="Vilon", cls="Peptide bioregulator",
       sub="A short 'bioregulator' dipeptide (immune/thymus)", evi="Evidence: Russian preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="Vilon is a short synthetic peptide bioregulator (a dipeptide) marketed toward immune/thymic function.",
       mech="<p>Proposed immune-directed bioregulation (Khavinson hypothesis); <strong>not independently established</strong>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Russian preclinical; no approval.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Peptide bioregulators (literature).", "PubMed: Khavinson peptide", pm("Khavinson peptide bioregulator")))),

  # ── Blends / stacks (combinations of the above) ────────────────────────
  dict(slug="cagrisema", name="CagriSema (Cagrilintide + Semaglutide)", cls="Peptide blend",
       sub="Amylin analog + GLP-1 agonist, co-formulated", evi="Evidence: Phase 3", evicls="b-evi-trial",
       reg="Investigational (combo)", regcls="b-reg", ruo=INVEST,
       what="CagriSema is an investigational co-formulation of <a href='cagrilintide.html'>cagrilintide</a> (amylin analog) and <a href='semaglutide.html'>semaglutide</a> (GLP-1).",
       mech="<p>It combines two complementary satiety pathways — amylin and GLP-1 — for greater weight effect than either alone.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Phase 3 program; <strong>not yet approved</strong>.</li></ul>",
       reg_html="<ul><li>Investigational; not approved.</li></ul>",
       refs=R(("Amylin + GLP-1 combination (literature).", "PubMed: CagriSema", pm("cagrisema cagrilintide semaglutide")))),
  dict(slug="bpc-tb500-oral", name="BPC-157 + TB-500 (Oral 500/500 mcg)", cls="Peptide blend",
       sub="Oral healing-peptide blend", evi="Evidence: preclinical (components)", evicls="b-evi",
       reg="RUO · WADA-prohibited", regcls="b-reg", ruo=RUO_WADA,
       what="A blend of <a href='bpc-157.html'>BPC-157</a> and <a href='tb-500.html'>TB-500</a>, the two most-discussed \"healing\" research peptides. Evidence and mechanism are those of the individual components (see each profile).",
       mech="<p>Combines BPC-157's proposed angiogenesis/NO effects with TB-500's actin/cell-migration effects — both preclinical.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>No trials on the blend; component data are preclinical with <strong>no Phase III</strong>.</li></ul>",
       reg_html="<ul><li>RUO; both components WADA-prohibited.</li></ul>",
       refs=R(("BPC-157/TB-500 background (literature).", "globalrph.com", "https://globalrph.com/2025/11/bpc-157-and-tb-500-background-indications-efficacy-and-safety/"))),
  dict(slug="glow-blend", name="Glow blend (BPC-157 / GHK-Cu / TB-500)", cls="Peptide blend",
       sub="A 'skin & recovery' research blend", evi="Evidence: preclinical (components)", evicls="b-evi",
       reg="RUO · WADA considerations", regcls="b-reg", ruo=RUO_WADA,
       what="\"Glow\" is a research blend combining <a href='bpc-157.html'>BPC-157</a>, <a href='ghk-cu.html'>GHK-Cu</a> and <a href='tb-500.html'>TB-500</a> — marketed for skin and recovery. See each component profile for the actual science.",
       mech="<p>Pools the components' proposed effects (healing peptides + copper skin peptide); studied only as individual compounds, not the blend.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>No blend trials; component evidence is preclinical/cosmetic.</li></ul>",
       reg_html="<ul><li>RUO; BPC-157/TB-500 are WADA-prohibited.</li></ul>",
       refs=R(("Component peptides (literature).", "globalrph.com", "https://globalrph.com/2025/11/bpc-157-and-tb-500-background-indications-efficacy-and-safety/"))),
  dict(slug="klow-blend", name="Klow blend (GHK-Cu / KPV / BPC-157 / TB-500)", cls="Peptide blend",
       sub="A four-peptide 'recovery & anti-inflammatory' blend", evi="Evidence: preclinical (components)", evicls="b-evi",
       reg="RUO · WADA considerations", regcls="b-reg", ruo=RUO_WADA,
       what="\"Klow\" combines <a href='ghk-cu.html'>GHK-Cu</a>, <a href='kpv.html'>KPV</a>, <a href='bpc-157.html'>BPC-157</a> and <a href='tb-500.html'>TB-500</a>. The science is that of the four components (see each profile).",
       mech="<p>Pools copper-peptide, anti-inflammatory tripeptide, and two healing peptides — all preclinical.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>No blend trials; component evidence is preclinical.</li></ul>",
       reg_html="<ul><li>RUO; some components WADA-prohibited.</li></ul>",
       refs=R(("Component peptides (literature).", "PMC7287585", RV))),
  dict(slug="wolverine-blend", name="Wolverine Blend (BPC-157 + TB-500)", cls="Peptide blend",
       sub="A 'recovery' blend of two healing peptides", evi="Evidence: preclinical (components)", evicls="b-evi",
       reg="RUO · WADA-prohibited", regcls="b-reg", ruo=RUO_WADA,
       what="A recovery-branded blend of <a href='bpc-157.html'>BPC-157</a> and <a href='tb-500.html'>TB-500</a>; the science is that of the components.",
       mech="<p>Combines the two most-discussed healing peptides — both preclinical, no Phase III.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>No blend trials; component data preclinical.</li></ul>",
       reg_html="<ul><li>RUO; both WADA-prohibited.</li></ul>",
       refs=R(("BPC-157/TB-500 background (literature).", "globalrph.com", "https://globalrph.com/2025/11/bpc-157-and-tb-500-background-indications-efficacy-and-safety/"))),
  dict(slug="hulk-blend", name="Hulk blend", cls="Peptide blend",
       sub="A proprietary GH-axis / growth blend", evi="Evidence: preclinical (components)", evicls="b-evi",
       reg="RUO · WADA considerations", regcls="b-reg", ruo=RUO_WADA,
       what="\"Hulk\" is a proprietary growth-oriented blend; exact contents vary by vendor and typically center on GH-axis peptides. Evidence is that of whatever individual components are included.",
       mech="<p>Proprietary; generally combines growth/GH-axis peptides. Because contents are non-standardized, no single mechanism applies — see the relevant component profiles.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>No standardized product or trials; <strong>evidence rests on individual components</strong>.</li></ul>",
       reg_html="<ul><li>RUO; GH-axis components are WADA-prohibited.</li></ul>",
       refs=R(("GH secretagogues (review).", "rco2.9", GHS))),
  dict(slug="lipo-b", name="Lipo-B", cls="Peptide blend",
       sub="A lipotropic 'fat-metabolism' injection (MIC + B12)", evi="Evidence: weak/none", evicls="b-evi",
       reg="Compounded · not FDA-approved as a combo", regcls="b-reg", ruo=RUO_STD,
       what="Lipo-B is a compounded \"lipotropic\" injection typically containing methionine, inositol, choline (MIC) plus vitamin B12.",
       mech="<p>The lipotropic components are involved in fat metabolism biochemically, but evidence that these injections cause meaningful fat loss is <strong>weak</strong>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>No robust trials showing weight-loss benefit from lipotropic injections.</li></ul>",
       reg_html="<ul><li>Compounded; the combination is not FDA-approved as a weight-loss product.</li></ul>",
       refs=R(("Lipotropic injections (literature).", "PubMed: lipotropic MIC injection", pm("lipotropic injection methionine inositol choline")))),
  dict(slug="lipo-c", name="Lipo-C", cls="Peptide blend",
       sub="A lipotropic 'fat-metabolism' injection (MIC + carnitine)", evi="Evidence: weak/none", evicls="b-evi",
       reg="Compounded · not FDA-approved as a combo", regcls="b-reg", ruo=RUO_STD,
       what="Lipo-C is a compounded lipotropic injection, generally MIC plus L-carnitine and B-vitamins.",
       mech="<p>Same lipotropic rationale as <a href='lipo-b.html'>Lipo-B</a>, adding carnitine; robust human fat-loss evidence is <strong>lacking</strong>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>No robust trials.</li></ul>",
       reg_html="<ul><li>Compounded; not FDA-approved as a weight-loss product.</li></ul>",
       refs=R(("Lipotropic injections (literature).", "PubMed: lipotropic injection", pm("lipotropic injection weight loss")))),
  dict(slug="lipo-mino", name="Lipo-Mino Mix", cls="Peptide blend",
       sub="A lipotropic + amino-acid + B-vitamin injection", evi="Evidence: weak/none", evicls="b-evi",
       reg="Compounded · not FDA-approved as a combo", regcls="b-reg", ruo=RUO_STD,
       what="Lipo-Mino Mix is a compounded injection combining lipotropics (MIC), amino acids and B-vitamins.",
       mech="<p>Lipotropic/amino/B-vitamin blend; the individual ingredients have metabolic roles but the combination's weight-loss efficacy is <strong>not established</strong>.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>No robust trials for the blend.</li></ul>",
       reg_html="<ul><li>Compounded; not FDA-approved as a weight-loss product.</li></ul>",
       refs=R(("Lipotropic injections (literature).", "PubMed: lipotropic injection", pm("lipotropic injection")))),
  dict(slug="lipo-shredder", name="Lipo Shredder", cls="Peptide blend",
       sub="A proprietary lipotropic 'fat-loss' injection", evi="Evidence: weak/none", evicls="b-evi",
       reg="Compounded · not FDA-approved", regcls="b-reg", ruo=RUO_STD,
       what="\"Lipo Shredder\" is a proprietary lipotropic fat-loss injection blend; exact contents vary by provider.",
       mech="<p>Marketed on the same lipotropic rationale as other Lipo blends; robust efficacy evidence is <strong>lacking</strong> and formulations are non-standardized.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>No robust trials; non-standardized.</li></ul>",
       reg_html="<ul><li>Compounded; not FDA-approved.</li></ul>",
       refs=R(("Lipotropic injections (literature).", "PubMed: lipotropic injection", pm("lipotropic injection")))),
  dict(slug="dihexa-mb-tesofensine", name="Dihexa + Methylene Blue + Tesofensine (Oral)", cls="Peptide blend",
       sub="A proprietary cognitive/metabolic oral stack", evi="Evidence: preclinical (components)", evicls="b-evi",
       reg="RUO / investigational (components)", regcls="b-reg", ruo=RUO_STD,
       what="A proprietary oral stack combining Dihexa (an angiotensin-derived pro-cognitive peptide), <a href='methylene-blue.html'>methylene blue</a>, and <a href='tesofensine.html'>tesofensine</a>. See component notes; Dihexa itself is preclinical.",
       mech="<p>Dihexa is studied preclinically for synaptogenesis (HGF/c-Met pathway); methylene blue for mitochondrial/redox effects; tesofensine as an appetite-suppressing reuptake inhibitor. Combining them is not studied as a unit.<sup><a href='#r1'>1</a></sup> Note methylene blue's dangerous serotonergic interactions.</p>",
       evidence="<ul><li>No blend trials; component evidence ranges from preclinical (Dihexa) to Phase 2 (tesofensine).</li></ul>",
       reg_html="<ul><li>Not approved as a blend; components are RUO/investigational. Serotonergic interaction risk (methylene blue).</li></ul>",
       refs=R(("Dihexa / synaptogenic peptides (literature).", "PubMed: dihexa", pm("dihexa synaptogenesis"))), disc="Contains methylene blue, which has dangerous drug interactions; use only under a licensed professional."),
  dict(slug="slu-pp-332-5amino1mq", name="SLU-PP-332 + 5-Amino-1MQ (Oral)", cls="Peptide blend",
       sub="An oral metabolic 'exercise-mimetic' stack", evi="Evidence: preclinical (components)", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="An oral stack of <a href='slu-pp-332.html'>SLU-PP-332</a> (ERRα agonist) and <a href='5-amino-1mq.html'>5-Amino-1MQ</a> (NNMT inhibitor) — both preclinical metabolic small molecules.",
       mech="<p>Pairs an ERRα \"exercise-mimetic\" with an NNMT inhibitor; both act on energy metabolism in rodent models. No human data on either or the combination.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Preclinical components; <strong>no human trials</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("ERRα / NNMT metabolic research (literature).", "PubMed: SLU-PP-332", pm("SLU-PP-332 NNMT")))),
  dict(slug="slu-pp-332-bam15", name="SLU-PP-332 + BAM-15", cls="Peptide blend",
       sub="An oral metabolic small-molecule stack", evi="Evidence: preclinical (components)", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="A stack of <a href='slu-pp-332.html'>SLU-PP-332</a> (ERRα agonist) and <a href='bam-15.html'>BAM-15</a> (mitochondrial uncoupler) — both preclinical.",
       mech="<p>Combines an oxidative-metabolism agonist with a mitochondrial uncoupler; both raise energy expenditure in rodents. Uncoupling has a narrow safety margin; no human data.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Preclinical components; <strong>no human trials</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("Metabolic small molecules (literature).", "PubMed: BAM-15", pm("BAM-15 uncoupler")))),
  dict(slug="cjc-1295-no-dac", name="CJC-1295 (No DAC)", cls="GH secretagogue",
       sub="A short-acting GHRH analog (Mod-GRF 1-29)", evi="Evidence: preclinical / early", evicls="b-evi",
       reg="RUO · WADA-prohibited", regcls="b-reg", ruo=RUO_WADA,
       what="CJC-1295 without DAC (often \"Mod-GRF 1-29\") is a short-acting GHRH analog, commonly paired with a ghrelin mimetic (see <a href='cjc-1295-ipamorelin.html'>CJC-1295 + Ipamorelin</a>).",
       mech="<p>As a GHRH-receptor agonist it prompts a physiological, pulsatile GH release. Without the DAC (drug-affinity-complex) it is <strong>short-acting</strong> — unlike the DAC version, which binds albumin and lasts days.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Preclinical/early human PK; <strong>not an approved therapy</strong>.</li></ul>",
       reg_html="<ul><li>RUO; GH secretagogues are WADA-prohibited (S2).</li></ul>",
       refs=R(("GH secretagogues / GHRH analogs (review).", "rco2.9", GHS))),
  dict(slug="5-amino-1mq-oral", name="5-Amino-1MQ (Oral)", cls="Metabolic research",
       sub="Oral form of the NNMT inhibitor", evi="Evidence: preclinical", evicls="b-evi",
       reg="RUO · not approved", regcls="b-reg", ruo=RUO_STD,
       what="An oral presentation of <a href='5-amino-1mq.html'>5-Amino-1MQ</a>, the NNMT-inhibitor small molecule studied in fat metabolism. See the full <a href='5-amino-1mq.html'>5-Amino-1MQ profile</a>.",
       mech="<p>Same proposed NNMT-inhibition mechanism (raising cellular NAD⁺, shifting fat-cell metabolism) as the base compound; all preclinical.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>Preclinical only; <strong>no human trials</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; RUO.</li></ul>",
       refs=R(("NNMT inhibition & metabolism (literature).", "PubMed: 5-Amino-1MQ", pm("5-Amino-1MQ NNMT")))),
  dict(slug="slu-pp-332-orforglipron", name="SLU-PP-332 + Orforglipron", cls="Peptide blend",
       sub="An 'exercise-mimetic' + oral GLP-1 stack", evi="Evidence: mixed (components)", evicls="b-evi",
       reg="RUO + investigational (components)", regcls="b-reg", ruo=RUO_STD,
       what="A stack of <a href='slu-pp-332.html'>SLU-PP-332</a> (preclinical ERRα agonist) and <a href='orforglipron.html'>orforglipron</a> (investigational oral GLP-1 agonist). The two have very different evidence levels.",
       mech="<p>Combines an oxidative-metabolism agonist with GLP-1 appetite/glucose effects; only orforglipron has human data, and the combination is not studied.<sup><a href='#r1'>1</a></sup></p>",
       evidence="<ul><li>SLU-PP-332 preclinical; orforglipron in Phase 3; <strong>combination unstudied</strong>.</li></ul>",
       reg_html="<ul><li>Not approved; components RUO/investigational.</li></ul>",
       refs=R(("Oral GLP-1 agonists (literature).", "PubMed: orforglipron", pm("orforglipron")))),
]
